# Generated by Django 4.2.9 on 2024-01-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_id', models.IntegerField()),
                ('R_name', models.CharField(max_length=255)),
                ('R_location', models.CharField(max_length=255)),
            ],
        ),
    ]
