# Generated by Django 4.2.9 on 2024-01-14 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='restaurant_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='base.items')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_menu',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.restaurant_menu'),
            preserve_default=False,
        ),
    ]
